# Generated by Django 6.0.3 on 2026-03-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionevent',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelTable(
            name='transactionevent',
            table='transaction_events',
        ),
    ]
